set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

#set (TOOLCHAIN_PATH "/opt/Xilinx/SDK/2019.1/gnu/aarch64/lin/aarch64-none/bin")
set (TOOLCHAIN_PATH "/opt/arm/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin")

set (CROSS_PREFIX           "${TOOLCHAIN_PATH}/aarch64-none-elf-")
set (CMAKE_C_COMPILER       "${CROSS_PREFIX}gcc" CACHE PATH "" FORCE)
set (CMAKE_CXX_COMPILER     "${CROSS_PREFIX}g++" CACHE PATH "" FORCE)
set (CMAKE_ASM_COMPILER     "${CROSS_PREFIX}gcc" CACHE PATH "" FORCE)
set (CMAKE_C_FLAGS          "${CMAKE_C_FLAGS} -DWAA400_UART_ENABLED -DLOG_INTERNAL_FIFO  -DLOG_FIFO_PLATFORM=2 -Os -g -mcpu=cortex-a53 -D__FILENAME__='\"$(notdir $(abspath $<))\"'")

set (CMAKE_C_COMPILER_WORKS 1)
set (CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

