set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

set (TOOLCHAIN_PATH "/opt/ModusToolbox/tools_2.4/gcc/bin")


set (CROSS_PREFIX           "arm-none-eabi-")
set (CMAKE_C_COMPILER       "${TOOLCHAIN_PATH}/${CROSS_PREFIX}g++" CACHE PATH "" FORCE)
set (CMAKE_CXX_COMPILER     "${TOOLCHAIN_PATH}/${CROSS_PREFIX}g++" CACHE PATH "" FORCE)
#set (CMAKE_C_FLAGS           "${CMAKE_C_FLAGS} -D__FILENAME__='\"$(notdir $(abspath $<))\"'")

set (CMAKE_C_COMPILER_WORKS 1)
set (CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

